[package]
name = "prospero-grad"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
image = { version = "0.25.6", features = ["png"] }
fidget = "0.3"

[profile.release]
overflow-checks = true
